CEA_CEMVS/src/Entity/Entrainement.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EntrainementRepository")
 */
class Entrainement
{
    use IdTrait;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Libelle;

    /**
     * @ORM\Column(type="datetime")
     */
    private $DateDebut;

    /**
     * @ORM\Column(type="datetime")
     */
    private $DateFin;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Salle;

    /**
     * @ORM\OneToMany(targetEntity="EntrainementTireur", mappedBy="entrainement")
     */
    private $tireurProfils;

    /**
     * @ORM\ManyToMany(targetEntity="User", mappedBy="maEntrainements")
     */
    private $maProfils;

    /**
     * @var EntrainementType
     * @ORM\ManyToOne(targetEntity="EntrainementType", inversedBy="entrainements")
     */

    private $entrainementType;



    /**
     * @ORM\OneToMany(targetEntity="Lecon", mappedBy="entrainement")
     */
    private $lecons;

    /**
     * @var TireurGroupe
     * @ORM\ManyToOne(targetEntity="TireurGroupe", inversedBy="entrainements")
     */

    private $tireurGroupe;

    public function __construct()
    {
        $this->tireurProfils = new ArrayCollection();
        $this->maProfils = new ArrayCollection();
        $this->lecons = new ArrayCollection();
    }

    public function getLibelle(): ?string
    {
        return $this->Libelle;
    }

    public function setLibelle(string $Libelle): self
    {
        $this->Libelle = $Libelle;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->DateDebut;
    }

    public function setDateDebut(\DateTimeInterface $DateDebut): self
    {
        $this->DateDebut = $DateDebut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->DateFin;
    }

    public function setDateFin(\DateTimeInterface $DateFin): self
    {
        $this->DateFin = $DateFin;

        return $this;
    }

    public function getSalle(): ?string
    {
        return $this->Salle;
    }

    public function setSalle(string $Salle): self
    {
        $this->Salle = $Salle;

        return $this;
    }

    public function addTireurProfil(EntrainementTireur $entrainementTireur) : Entrainement
    {
        if($this->tireurProfils->contains($entrainementTireur)){
            return $this;
        }
        $this->tireurProfils->add($entrainementTireur);

        return $this;
    }

    public function removeTireurProfil(EntrainementTireur $entrainementTireur) : Entrainement
    {
        if (!$this->tireurProfils->contains($entrainementTireur))
        {
            return $this;
        }
        $this->tireurProfils->removeElement($entrainementTireur);
        return $this;

    }

    /**
     * @return mixed
     */
    public function getTireurProfils()
    {
        return $this->tireurProfils;
    }

    public function getTireurProfilUsers()
    {
        $return = null;
        foreach ($this->tireurProfils as $k=>$profil)
        {
            $return[$k]=$profil->getTireur();
        }
        return $return;
    }

    public function addMaProfil(User $user) : Entrainement
    {
        if($this->maProfils->contains($user)){
            return $this;
        }
        $this->maProfils->add($user);
        $user->addMaEntrainement($this);
        return $this;
    }

    public function removeMaProfil(User $user) : Entrainement
    {
        if (!$this->maProfils->contains($user))
        {
            return $this;
        }
        $this->maProfils->removeElement($user);
        $user->removeMaEntrainement($this);
        return $this;

    }

    /**
     * @return mixed
     */
    public function getMaProfils()
    {
        return $this->maProfils;
    }

    public function addLecon(Lecon $lecon) : Entrainement
    {
        if($this->lecons->contains($lecon)){
            return $this;
        }
        $this->lecons->add($lecon);
        return $this;
    }

    public function removeLecon(Lecon $lecon) : Entrainement
    {
        if (!$this->lecons->contains($lecon))
        {
            return $this;
        }
        $this->lecons->removeElement($lecon);
        return $this;

    }

    /**
     * @return mixed
     */
    public function getLecons()
    {
        return $this->lecons;
    }

    /**
     * @return TireurGroupe
     */
    public function getTireurGroupe(): ?TireurGroupe
    {
        return $this->tireurGroupe;
    }

    /**
     * @param TireurGroupe $tireurGroupe
     */
    public function setTireurGroupe(?TireurGroupe $tireurGroupe): void
    {
        $this->tireurGroupe = $tireurGroupe;
    }

    /**
     * @return EntrainementType
     */
    public function getEntrainementType(): ?EntrainementType
    {
        return $this->entrainementType;
    }

    /**
     * @param EntrainementType $entrainementType
     */
    public function setEntrainementType(?EntrainementType $entrainementType): void
    {
        $this->entrainementType = $entrainementType;
    }

}

CEA_CEMVS/src/Entity/TireurGroupe.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TireurGroupeRepository")
 */
class TireurGroupe
{
    use IdTrait;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\OneToMany(targetEntity="User", mappedBy="tireurGroupe")
     */
    private $profils;

    /**
     * @ORM\OneToMany(targetEntity="Entrainement", mappedBy="tireurGroupe")
     */
    private $entrainements;

    public function __construct()
    {
        $this->entrainements = new ArrayCollection();
        $this->profils = new ArrayCollection();
    }
    public function getIdTrait(): ?int
    {
        return $this->IdTrait;
    }
    
    public function __toString(){
        return $this->Nom;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function addProfil(User $user) : TireurGroupe
    {
        if($this->profils->contains($user)){
            return $this;
        }
        $this->profils->add($user);
        return $this;
    }

    public function removeProfil(User $user) : TireurGroupe
    {
        if (!$this->profils->contains($user))
        {
            return $this;
        }
        $this->profils->removeElement($user);
        return $this;

    }

    /**
     * @return mixed
     */
    public function getProfils() 
    {
        return $this->profils;
    }



    public function addEntrainement(Entrainement $entrainement) : TireurGroupe
    {
        if($this->entrainements->contains($entrainement)){
            return $this;
        }
        $this->entrainements->add($entrainement);
        return $this;
    }

    public function removeEntrainement(Entrainement $entrainement) : TireurGroupe
    {
        if (!$this->entrainements->contains($entrainement))
        {
            return $this;
        }
        $this->entrainements->removeElement($entrainement);
        return $this;

    }

    /**
     * @return mixed
     */
    public function getEntrainements()
    {
        return $this->entrainements;
    }


}

CEA_CEMVS/src/Controller/ProfilController.php
<?php
namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class ProfilController extends Controller
{
    /**
     * @Route("/Profils")
     */
    public function ProfilsList(Request $request){
        $em=$this->getDoctrine()->getManager();
        $ProfilsRepository      = $em->getRepository(User::class);
        $Profils                = $ProfilsRepository->findAll();

        return $this->render('profil/profilListe.html.twig', [
            'Profils' => $Profils,
        ]);
    }

    /**
     * @Route("/Profil/{id}")
     */
    public function ProfilsVue(Request $request, User $profil){

        return $this->render('profil/profilVue.html.twig', [
            'Profil' => $profil,
        ]);
    }
}

CEA_CEMVS/templates/profil/profilListe.html.twig
{% extends 'base.html.twig' %}

{% block title %}
Profils
{% endblock %}

{% block body %}
    <div class="table-responsive">
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>#</th>
				<th>Login</th>
				<th>Nom</th>
				<th>Prenom</th>
				<th>Role</th>
				<th>Categorie</th>
				<th>Groupe</th>
            </tr>
            </thead>
            <tbody>
            {% set token = csrf_token('ENTRAINEMENT_DELETE') %}
            {% for Profil in Profils %}
            	{% if is_granted('ROLE_ADMIN') 
            	or ( Profil.role == 1 and is_granted('ROLE_MA')) 
            	%}                    
                <tr>
                    <td><a href="{{ path('app_profil_profilsvue',{id:Profil.id}) }}">{{ Profil.id }}</a></td>
					<td>{{ Profil.login }}</td>
					<td>{{ Profil.nom }}</td>
					<td>{{ Profil.prenom }}</td>
					{% if Profil.role == 1 %}<td>Tireur</td>{% endif %}
					{% if Profil.role == 2 %}<td>Maitre d'arme</td>{% endif %}
					{% if Profil.role == 3 %}<td>Admin</td>{% endif %}
					<td>{{ Profil.profilCategorie }}</td>
					<td>{{ Profil.tireurGroupe }}</td>

					{#% if is_granted('ROLE_ADMIN') %}
						<td><a class="btn btn-danger" href="{{ path('deleteEntrainement',{id:Entrainement.id,token:token, saison:saison}) }}">Supprimer</a></td>
                    {% endif %}
					{% if is_granted('ROLE_TIREUR') and app.user not in Entrainement.tireurProfilUsers %}
						<td><a class="btn btn-success" href="{{ path('sinsrireEntrainement',{id:Entrainement.id,token:token2, saison:saison}) }}">S'inscrire</a></td>
					{% endif %#}
                </tr>
                {% endif %}
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

CEA_CEMVS/templates/profil/profilVue.html.twig
{% extends 'base.html.twig' %}

{% block title %}
Profils
{% endblock %}

{% block body %}
    <div class="table-responsive">
        <table class="table table-bordered">
            <thead>
            <tr>
				<th>Login</th>
				<th>Nom</th>
				<th>Prenom</th>
				<th>Role</th>
				<th>Categorie</th>
				<th>Groupe</th>
            </tr>
            </thead>
            <tbody>
            {% set token = csrf_token('ENTRAINEMENT_DELETE') %}
            <tr>
				<td>{{ Profil.login }}</td>
				<td>{{ Profil.nom }}</td>
				<td>{{ Profil.prenom }}</td>
				{% if Profil.role == 1 %}<td>Tireur</td>{% endif %}
				{% if Profil.role == 2 %}<td>Maitre d'arme</td>{% endif %}
				{% if Profil.role == 3 %}<td>Admin</td>{% endif %}
				<td>{{ Profil.profilCategorie }}</td>
				<td>{{ Profil.tireurGroupe }}</td>

				{#% if is_granted('ROLE_ADMIN') %}
					<td><a class="btn btn-danger" href="{{ path('deleteEntrainement',{id:Entrainement.id,token:token, saison:saison}) }}">Supprimer</a></td>
                {% endif %}
				{% if is_granted('ROLE_TIREUR') and app.user not in Entrainement.tireurProfilUsers %}
					<td><a class="btn btn-success" href="{{ path('sinsrireEntrainement',{id:Entrainement.id,token:token2, saison:saison}) }}">S'inscrire</a></td>
				{% endif %#}
            </tr>
            </tbody>
        </table>
    </div>
{% endblock %}